# Generated by Django 5.0.4 on 2024-05-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['product']},
        ),
    ]
