# Generated by Django 5.0.4 on 2024-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_ordercheckout_address_ordercheckout_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Credit card', 'Credit card'), ('Google Pay', 'Google Pay')], max_length=100, null=True),
        ),
    ]
