# Generated by Django 5.0.4 on 2024-05-15 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_ordercheckout_payment_method'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercheckout',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
