# Generated by Django 5.0.4 on 2024-05-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favitem',
            options={'ordering': ['product']},
        ),
        migrations.AlterModelOptions(
            name='favoriteproducts',
            options={'ordering': ['-owner']},
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
