# Generated by Django 5.0.4 on 2024-05-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_products', '0002_alter_favitem_options_alter_favoriteproducts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproducts',
            name='items',
            field=models.ManyToManyField(null=True, to='fav_products.favitem'),
        ),
    ]
