# Generated by Django 5.0.4 on 2024-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_products', '0004_alter_favoriteproducts_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproducts',
            name='items',
            field=models.ManyToManyField(blank=True, to='fav_products.favitem'),
        ),
    ]
