# Generated by Django 5.0.4 on 2024-04-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_collection_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='body',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
