# Generated by Django 5.0.4 on 2024-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_collection_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='category_images'),
        ),
    ]
