# Generated by Django 5.0.4 on 2024-04-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['product__title']},
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], max_length=100),
        ),
    ]
